name: Pipelines

on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  capabilitiesToResources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Install packages
        run: npm i
      - name: Run
        run: npm run capabilitiesToResources
  allResourcesToUtilsRepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Install packages
        run: npm i
      - name: Run
        run: npm run allResourcesToUtilsRepo
  utilsRepoToAllResources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Install packages
        run: npm i
      - name: Run
        run: npm run utilsRepoToAllResources
  validateJsons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Install packages
        run: npm i
      - name: Run
        run: npm run validateJsons
  validateTranslations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Install packages
        run: npm i
      - name: Run
        run: npm run validateTranslations